# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FoodEfficiency
email: info@foodefficiency.eu
description: >- # this means to ignore newlines until "baseurl:"
  FoodEfficiency - Your professional business partner for quality,
  environmental and CSR related tasks within the food manufacturing industry
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foodefficiency.eu" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
# remote_theme: FoodEfficiency/minima
plugins:
  - jekyll-feed
social_links:
  email: info@foodefficiency.eu
  email_subject: Kontakt via hjemmeside
  linkedin: karin-hansen-a14446
  phone: +45 2987 8494

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

# I18n - default language and definitions
lang: da
languages:
  - da:
    title: Dansk
    img: /assets/img/da.png
    lang: da
    url: /
    # posts_url: /news
  - en:
    title: English
    img: /assets/img/en.png
    lang: en
    url: /en
    # posts_url: /en/news

# News / Posts
# Note: pagination cannot be used with permalink!
# paginate: 2
# paginate_path: "/blog/page:num/" # will read blog/index.html (not translated?)
show_excerpts: true
sidebar_posts_limit: 3

# New directory structure
collections_dir: content
collections:
  da:
    output: true
    permalink: /:collection/:slug
    # sort_by: index
    # pages:
    #   sort_by: index
    #   order:
    #     - references.md
    #     - links.md
    #     - about.md
  en:
    output: true
    permalink: /:collection/:slug

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
  -
    scope:
      path: ""
      type: "da"
    values:
      layout: "page"
  -
    scope:
      path: "_da/pages"
      type: "da"
    values:
      layout: "page"
      lang: "da"
      permalink: "/:slug"
  -
    scope:
      path: "_da/posts"
    values:
      layout: "post"
      lang: "da"
      # permalink: /da/post/:slug
      permalink: /news/:slug
      collection: "posts"
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "page"
  -
    scope:
      path: "_en/pages"
      type: "en"
    values:
      layout: "page"
      lang: "en"
      permalink: "/en/:slug"
  -
    scope:
      path: "_en/posts"
    values:
      layout: "post"
      lang: "en"
      permalink: /en/news/:slug
